// 文案来自任务 003 与定稿；后续由设计负责人维护。
export const c = {
    app: 'DispatchDock', tasks: '任务', connect: '连接', settings: '设置', about: '关于', placeholder: '【待 004 实现】', protocol: '文件协议 v1',
    status: { run: '进行中', done: '已完成', fail: '失败', stop: '已中断' },
    all: '全部', issues: '失败或中断', projects: '全部项目', import: '导入旧任务', today: '今天', yesterday: '昨天',
    running: (n: number) => n ? `${n} 个任务进行中` : '没有进行中的任务',
    empty: '还没有派发过任务', emptyHelp: '在 Claude Code 或 Devin 里让它"交给 Codex 做……"，派出的任务会出现在这里。',
    select: '选择一个任务', emptyDetail: '这里会显示任务的进展和汇报', detailHelp: '进展、汇报、改动的文件和派发参数都在这里看。',
    stop: '停止', more: '更多', cancel: '取消', stopTitle: (name: string) => `停止「${name}」？`, stopBody: 'Codex 会立刻结束，工作区里没提交的改动会保留。', changed: '任务状态已经变了，请重试',
    flow: '进展', report: '汇报', files: '改动', params: '参数', think: '显示思考', plan: '计划', follow: '正在跟随最新进展', latest: '跳到最新',
    closed: '派发会话已关闭', readonly: '只读任务', started: '开始', minutes: '分钟', elapsed: '用时', commit: '提交', runningCmd: '运行中…',
    failedTitle: (exit: number | null | undefined) => `Codex 异常退出（exit=${exit}）`, failedHelp: '原因见最后一条。要重试，在派活方的会话里重新派发；工作区里没提交的改动会保留。',
    interruptedTitle: '派发会话关闭，任务被一起中断', interruptedHelp: '任务是派发会话的子进程。在设置里打开"托管"后，关掉会话也不会中断任务。',
    reportLater: '任务结束后显示汇报', noReport: '没有汇报', noReportHelp: '任务没有正常结束，Codex 没来得及写汇报。看"进展"了解停在哪里。',
    noFiles: '没有改动文件', filesHelp: '按 Codex 报告的改动汇总', filesLive: '，任务进行中会继续增加', kinds: { add: '新增', update: '修改', delete: '删除' },
    open: '打开', openRepo: '打开仓库文件夹', openSpec: '打开任务说明', openReport: '打开汇报文件', openProgress: '打开进度文件', copyName: '复制记录名', hide: '从列表隐藏',
    record: '记录名', spec: '任务说明', direct: '直接给的任务文字', role: '角色', noRole: '不指定', dispatcher: '派活方', agent: '干活方', model: '模型', effort: '推理强度', tier: '档位', sandbox: '沙箱', repo: '仓库', records: '记录文件', progress: '进度', events: '统一事件', raw: '原始输出', followCodex: '跟随 Codex', turn: '一轮结束', input: '输入', output: '输出',
    error: '操作没有完成，请重试', earlier: '加载更早的进展', unknownHost: '其他派活方',
    // 用户在本软件里停止的任务（signal 为 stopped-by-app）
    stopped: '你停止了这个任务', stoppedHelp: '工作区里没提交的改动还在。要继续，在派活方的会话里重新派发。', stoppedShort: '手动停止',
    managed: '托管', yes: '是', no: '否', goSettings: '去设置', managedOn: '托管已开启', managedOff: '托管未开启',
    imported: '导入的旧任务', planNow: '当前',
};

// 以下逐项取自 004 任务说明与界面定稿。
export const p = {
    subtitle: '谁在派活、谁在干活', detect: '重新检测', detected: '已检测到', missingHost: '未检测到',
    dispatchers: '派活方', workers: '干活方', dispatchHelp: '在这些工具里装上技能，它们就能把工作派给 Codex。装之前会备份原来的版本，可以回退。', workerHelp: '实际执行任务的程序。v0.1 只支持 Codex CLI。',
    hostMissing: (host: string) => `没有找到 ${host}。装好以后点右上角"重新检测"。`,
    latest: '最新', update: (version: string) => `可更新到 ${version}`, missing: '未安装', custom: '自己改过的版本', protected: '不会自动替换',
    actions: { install: '安装', update: '更新', reinstall: '重新安装', rollback: '回退', replace: '备份后替换…' } as Record<string, string>,
    replace: '替换', rollbackTitle: (host: string) => `回退「${host}」的技能？`, rollbackBody: '回到上一次操作之前的状态。当前版本会先备份，之后还能再回退。',
    replaceTitle: (skill: string) => `替换「${skill}」？`, replaceBody: '这份不是 DispatchDock 装的，或者装好后被改过。替换前会先备份，随时可以回退。',
    customHelp: '这份 codex-dispatch 不是 DispatchDock 装的，或者装好后被改过。更新时默认跳过它；要换成公开版，先备份再替换，随时可以回退。',
    dependency: 'dual-role-workflow 需要 codex-dispatch', backupHint: '替换前会备份', updateHint: '更新前会备份，可以回退',
    installed: (n: number) => `已安装 ${n} 个 · 可以回退`, rolledBack: '已回退',
    lastInstall: (time: string) => `上次安装 ${time}`,
    runnable: '可以运行', notFound: '找不到', codexMissing: '找不到 Codex CLI', codexHelp: '确认在终端里能运行 codex --version。用 pnpm、scoop 这类方式装的，可以手动指定 Codex 的位置。',
    version: '版本', location: '位置', login: '登录', auto: '自动查找', choose: '指定位置…', reset: '改回自动查找',
    loginStates: { in: '已登录', out: '未登录', unknown: '无法确定' } as Record<string, string>,
    versionChange: (old: string, next: string) => `Codex 从 ${old} 升级到了 ${next}。如果任务进展里出现大量没整理过的原始文本，可能是它的输出格式变了。`, ack: '知道了',
    defaults: '派发默认值', defaultsHelp: '派活方派发时没有单独指定的，就用这里的值。"跟随 Codex"表示不传这个参数，由 Codex 自己的配置决定。单次任务的参数（例如调研用只读）仍由派活方决定。',
    follow: (value?: string) => `跟随 Codex（${value || '未设置'}）`, customModel: '自定义…', currentHelp: '括号里是 Codex 现在的配置',
    tier: '服务档位', sandboxHelp: '派出的工作要写文件、提交，所以默认可写工作区', writable: '可写工作区', readonly: '只读',
    override: (name: string, value: string) => `环境变量 ${name} 正在覆盖这一项（${value}）`,
    watch: '进度窗口', watchTitle: '弹出只读进度窗口', watchHelp: '"自动"：本软件开着时不弹，在这里看；没开时弹出终端窗口', watchOptions: ['自动', '总是', '从不'],
    notifications: '通知', notify: '任务结束时通知', notifyHelp: '完成、失败、中断都会通知；点通知直接打开这个任务',
    appearance: '外观', theme: '主题', themes: ['跟随系统', '浅色', '深色'], config: '配置文件', openFolder: '打开所在文件夹',
    configError: (reason: string) => `config.json 无法读取（${reason}）。修好或删掉它之后，这里才能修改派发默认值。`,
    steps: ['检测', '技能', '默认值'], welcome: '欢迎使用 DispatchDock', welcomeHelp: '它让 Claude Code、Devin 把工作派给 Codex，你在这里统一查看、停止和验收。先看看这台电脑上有什么。',
    installSkills: '安装技能', installHelp: '技能装在派活方里，告诉它怎么派活、怎么看结果。已有的版本会先备份。',
    skillHelp: { 'codex-dispatch': '派活、看进度、收汇报', 'dual-role-workflow': '可选：让对话的模型当设计负责人，Codex 做执行' } as Record<string, string>,
    customChoice: '已有自己改过的版本，勾选后会先备份再替换', wizardDefaults: '不确定就保持"跟随 Codex"，以后在设置里随时改。',
    next: '下一步', previous: '上一步', skip: '跳过', installNext: '安装并继续', finish: '完成', rerun: '重新运行首次引导',
    about: '让 Claude Code、Devin 把工作派给 Codex，在这里统一查看、停止和验收。',
    detecting: '正在检测…', installing: '正在安装…',
    // 本机已装版本比软件自带的新：不提供更新，避免反向降级
    newer: '比软件自带的新',
    // 引导第 2 步每一项右侧的状态
    wizardLatest: '已是最新', wizardCustom: '自己改过的版本',
    // 卡片底部平时的说明（操作完成后的"已安装 N 个"只显示 3 秒）
    customIdle: '替换前会备份',
    managed: '托管', managedHelp: '任务默认是派活方会话的子进程，关掉会话可能连带中断任务。',
    managedToggle: '由 DispatchDock 托管任务', managedToggleHelp: '打开后，派出的任务由本软件启动。关掉 Claude Code 或 Devin 的会话，任务照常进行；要停止就在这里停。软件没开时，任务照旧由派活方启动。',
    wizardManaged: '托管任务', wizardManagedHelp: '关掉派活方的会话也不中断任务',
};
